
#
default: &default
  adapter: postgresql
  encoding: unicode
  username:
  pool: 5

development:
  <<: *default
  database: belt_exam_development

test:
  <<: *default
  database: belt_exam_test

production:
  <<: *default
  database: belt_exam_production
  username: ubuntu
  password: <%= ENV['BELT_EXAM_DATABASE_PASSWORD'] %>
