# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da827f20e75da64285dfdd322234a70c447e1764ae97492b68e51974d9d29fc6584293dd121d189c4efef8d3c2890f8753e94bcfd59bba3d1e0197470edf2eb6

test:
  secret_key_base: 8444d8dd07e2b7176575404c3b09c2af98633e3591b8cb3f1f69da3989cdb3fe32a0afafeaf5169ec8a301f12809680460345b7b0e13847f81d43efccef49b40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
